### ISSUE TITLE
Problems with Admin User

### ISSUE THREAD

**Issue by danromex** [leeb003/LCM-Leads-and-Contacts-Manager#2]
Hello, Good morning
I installed LCM as it says in the instructions but I could not login with the admin user, I went to PHPmyAdmin and I realized that no admin user was created. So I made my admin user, I added it manually but I can't login. I wanted to ask for your support to be able to create the user correctly. I am sending you a screenshot.
I apprecciate your help.

![Captura](https://user-images.githubusercontent.com/9160663/124389371-5eece080-dcac-11eb-8b58-3e0c1663481a.PNG)

**Comment by danromex** [comment]
I installed the app in this domain: https://www.escuderiatotalcar.ml/lcm

**Comment by danromex** [comment]
Its possible to give me a database example with admin user? I created a user, and i dont know in what format is the pasowrd, i put MD5, PASSWORD, and i cant login. Thanks

**Comment by leeb003** [comment]
The passwords use a sha1 SALT mechanism as stated in classes/variables.php which shouldn't change unless you recreate all passwords.  Regardless, the installation process has a few updates in 1.4.0 that correct some installation issues that might have affected you before.
